### ISSUE TITLE
Restructure .R files

### ISSUE THREAD

**Issue by maurolepore** [forestgeo/AGBfluxes#18]
What are your main functions? There should be one .R file per main function and its helpers.

**Comment by ervanSTRI** [comment]
What do you mean? Can't be a single R code containing all functions? Isn't the helpers included in the header of the function??

**Comment by maurolepore** [comment]
> Can't be a single R code containing all functions? 

Yes, you can put all functions in a single .R file. The package will work regardless of your how you organize the functions in files. But the package is easier to understand and maintain if you have a structure like this:

R/main-function-1.R
R/main-function-2.R
R/...

tests/testthat/test-main-function1.R
tests/testthat/test-main-function2.R
tests/testthat/...

**Comment by maurolepore** [comment]
I kind of did this already, by renaming the file to data_preparation.R.
