### ISSUE TITLE
PRIORITY: Help me run data_preparation()

### ISSUE THREAD

**Issue by maurolepore** [forestgeo/AGBfluxes#20]
RE: On Thu, Oct 4, 2018 at 8:22 AM Ervan Rutishauser <er.rutishauser@gmail.com> wrote:
> The main function works fine on my end. Could you test and let me know, please?

Unfortunately it fails on my end. I tried from the AGBfluxes package itself, and from a new project with just the data (image below). Can you see what I'm doing wrong?

![image](https://user-images.githubusercontent.com/5856545/46481077-8a230800-c7c0-11e8-9a8d-d9ace81ff06a.png)

**Comment by maurolepore** [comment]
BTW, when you succeed running `data_preparation()`, is that with a fresh session? I'm afraid you may have something loaded in your global environment that I don't.

**Comment by maurolepore** [comment]
@ervanSTRI , 

This issue is the priority.

Please help me figure out why run `data_preparation()` fails to run from a fresh R environment (an R session other than yours). The next step is for you to run `data_praparation()` from [this rstudio.cloud project](https://rstudio.cloud/project/103269). Save a permanent copy so it remains in your rstudio.cloud account:

![image](https://user-images.githubusercontent.com/5856545/46608176-d37d9b00-cad1-11e8-9053-4d35a55c7e2b.png)

That project is a clone of AGBfluxes, and the R environment is completely fresh. This means that nothing from your own computer will interfere (e.g. stuff in your .Rprofile, global environment, environmental variable, etc.).

From that rstudio.cloud project you can pull and push to GitHub as us usual. You may need to tell git who you are:

```bash
git config --global user.name "username"
git config --global user.email "you@example.com"
```

This should help you find the errors that you may not get in your own computer. Try to fix them if you can, and let me know if you can't.

**Comment by maurolepore** [comment]
@ervanSTRI,

When you run `data_preparation()` successfully, Did you run it from a fresh session (i.e. after pressing Shift + Control + F10)? I still get the error I show below. Also, this works, please send me your output (maybe as an .Rdata file -- or write a .csv file).

![image](https://user-images.githubusercontent.com/5856545/46843677-f34ae280-cda1-11e8-8a51-a75d9af56f50.png)

**Comment by ervanSTRI** [comment]
I fixed the problem. For whatever reason, some mandatory data set included in BIOMASS aren't loaded. I add to debug, catch the data and save it into /data. This is tedious and probably not very clean. We might want to explore that to understand what happen and why the external functions do not work. 
At least, the function now works properly. 
I noticed another issue: the ggplot (aes) isn't working at last step, despite the fact that "ggplot2" is mentioned in "import" file. In fact, it seems that both packages ("BIOMASS" and "ggplot2" ) fail to be loaded properly. Maybe we declare them again in the main function  # @imports ...  ???

**Comment by maurolepore** [comment]
> At least, the function now works properly.

Unfortunately, it doesn't run neither in my computer nor in rstudio.cloud. Please confirm that you are runing the same code (see below),  and that your session is fresh -- meaning that:

1. You restart before you run (Shift + Control + F10) 
2. Your global options are set as I show you below -- which avoids your current session from loading stuff from older sessions.

Finally, once you do this please share your output as I explained in https://github.com/forestgeo/AGBfluxes/issues/20#issuecomment-429180272.


## Code and output

```r
# Document: devtools::document() or (Shift + Control + D)
# Build: devtools::build() or Shift + Control + B)
# Install: devtools::install() or click Install and Restart
# Restart session (Control + Shift + F10)

library(AGBfluxes)

data_preparation(
  site = "barro colorado island",
  stem = TRUE,
  taper_correction = TRUE,
  fill_missing = TRUE,
  use_palm_allometry = TRUE,
  flag_stranglers = TRUE,
  dbh_stranglers = 500,
  maxrel = 0.2,
  output_errors = TRUE,
  DATA_path = NULL,
  exclude_interval = NULL
)
```

![image](https://user-images.githubusercontent.com/5856545/46885710-c7be0b80-ce26-11e8-8263-13deef692af8.png)

## Tools > Global Options

![image](https://user-images.githubusercontent.com/5856545/46884992-a0fed580-ce24-11e8-964c-96eb5b653bb3.png)

**Comment by maurolepore** [comment]
> ... ggplot (aes) isn't working at last step, despite the fact that "ggplot2" is mentioned in "import" file. 

This is surprising. Unfortunately I can't reproduce this until I get the some output. In the mean time, I'll refer to all functions in __ggplot2__ explicitely (as `ggplot2::function()`). Then we can remove __ggplot2__ from imports. This will make the code quite messy but I don't worry for now. I'll cleanup once I can test the outputs.

**Comment by maurolepore** [comment]
> ... it seems that both packages ("BIOMASS" and "ggplot2" ) fail to be loaded properly....For whatever reason, some mandatory data set included in BIOMASS aren't loaded.

I'm exploring __BIOMASS__

**Comment by maurolepore** [comment]
Good news. I found the data in BIOMASS/data on CRAN's GitHub. I document this in data-raw/data-BIOMASS_package.R. 

* Use BIOMASS' data as internal data.
* Clenup.

**Comment by maurolepore** [comment]
This ends my cleanup for now. I hope you can make `data_preparation()` run and I'll follow from there. A good place to ensure that runs not only for you but for any user is in README.Rmd. If you knit the file and the output shows an error, then something is wrong. Knitr runs a fresh sesison every time you knit. Notice, however, that after you fix the package and re-install it, you may need to Clear Kniter's Cache:

![](https://i.imgur.com/w4aPgq2.png)
