### ISSUE TITLE
Fix dataset bci_stem_1995: It has 0 rows.

### ISSUE THREAD

**Issue by maurolepore** [forestgeo/AGBfluxes#3]

**Comment by ervanSTRI** [comment]
Done, but I can't push the data...

**Comment by maurolepore** [comment]
Why can't you push? Can you give me some detail? Can you push other things but not the data? Do you get any error message that might guide us towards a solution?

**Comment by ervanSTRI** [comment]
That's the message I get: 
>>> C:/Program Files/Git/bin/git.exe pull
error: Pulling is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.

**Comment by maurolepore** [comment]
It seems like you need to first pull, then push.

**Comment by ervanSTRI** [comment]
Solved
